dist: bionic
# see https://docs.travis-ci.com/user/languages/python/
language: python
# python versions to be tested
python:
#  - "2.7" # see https://github.com/WolfgangFahl/gremlin-python-tutorial/issues/7
  - "3.6"
  - "3.7"
  - "3.8"
services:
# allow gui output
  - xvfb
# allow use of docker  
  - docker
before_install:
  # install some renderers
  # check version
  - lsb_release -a
install:
  - echo $USER
# command to run tests
script:
# command to install dependencies
  - scripts/install
# command to run Dgraph
  # pull dgraph
  - scripts/dgraph -p
  # run dgraph
  - scripts/dgraph
  # pull and run weaviate
  - scripts/weaviate
# command to run tests
  - scripts/test
  # show log results
  - cat /tmp/alpha.log
  - cat /tmp/zero.log
  - cat /tmp/ratel.log
