#!/bin/bash
#
# Weaviate with an English Contextionary
#

# port to run weaviate at
port=8153
# maximum number of seconds to wait for weaviate startup
MAX_WAIT_SECONDS=60

#ansi colors
#http://www.csc.uvic.ca/~sae/seng265/fall04/tips/s265s047-tips/bash-using-colors.html
blue='\033[0;34m'
red='\033[0;31m'
green='\033[0;32m' # '\e[1;32m' is too bright for white bg.
endColor='\033[0m'

#
# a colored message
#   params:
#     1: l_color - the color of the message
#     2: l_msg - the message to display
#
color_msg() {
  local l_color="$1"
  local l_msg="$2"
  echo -e "${l_color}$l_msg${endColor}"
}

#
# error
#
# show the given error message on stderr and exit
#
#   params:
#     1: l_msg - the error message to display
#
error() {
  local l_msg="$1"
  # use ansi red for error
  color_msg $red "Error:" 1>&2
  color_msg $red "\t$l_msg" 1>&2
  exit 1
}


# show usage
#
usage() {
  echo "$0 [-h|--help|-k|--kill]"
  echo ""
  echo "-h | --help: show this usage"
  echo "-k | --kill: stop the docker compose services"
  exit 1
}

which docker-compose
if [ $? -ne 0 ]
then
  error "docker-compose needs to be installed for weaviate to run"
fi

# Download the Weaviate configuration file
download() {
  curl -O https://raw.githubusercontent.com/semi-technologies/weaviate/0.22.14/docker-compose/runtime/en/config.yaml
  # Download the Weaviate docker-compose file
  curl -O https://raw.githubusercontent.com/semi-technologies/weaviate/0.22.14/docker-compose/runtime/en/docker-compose.yml
  cat docker-compose.yml | sed s/8080/$port/g > /tmp/docker-compose.yml
  mv /tmp/docker-compose.yml docker-compose.yml
  # Run Docker Compose
}

#
# wait for weaviate to start
#
wait4Weaviate() {
  ALREADY_WAITING=0
  color_msg $blue "waiting for weaviate to start "
  while true; do
    if curl -s http://localhost:$port > /dev/null; then
        break
    else
      echo -n "."
      if [ $ALREADY_WAITING -gt $MAX_WAIT_SECONDS ]; then
        error "Weaviate did not start up in $MAX_WAIT_SECONDS."
      else
        sleep 2
        let ALREADY_WAITING=$ALREADY_WAITING+2
      fi
    fi
  done
  echo "."
  color_msg $green "weaviate is up and running on port $port"
}

stage=$HOME/source/docker/Weaviate
if [ ! -d $stage ]
then
  color_msg $blue creating "$stage"
  mkdir -p $stage
fi
cd $stage

if [ $# -lt 1 ]
then
  download
  docker-compose up -d
  wait4Weaviate
fi
# commandline option
while [  "$1" != ""  ]
do
  option="$1"
  case $option in
    -k|--kill) docker-compose down;;
    -h|--help) usage;;
  esac
  shift
done
